name: Run tests

on: 
  push:
    branches:
      - dev
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1']
        julia-arch: [x64]
        os: [ ubuntu-latest ]
        mongodb-version: ['4.2', '4.4']

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Julia setup
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      
      - name: Build Julia Project
        uses: julia-actions/julia-buildpkg@v1

      - name: Run Julia Project
        uses: julia-actions/julia-runtest@v1
        # with:
        #   annotate: true